/** Genre choices offered in the upload and edit forms. Keep in sync with the edit_track_once command's genre max length (64). */
export const GENRES = [
  "Soul",
  "R&B",
  "Funk",
  "Neo-Soul",
  "Gospel",
  "Motown",
  "Blues-Soul",
  "Soul Ballad",
  "Jazz",
  "Hip Hop",
  "Rap",
  "Trap Soul",
  "Amapiano",
  "Afrobeats",
  "Gqom",
  "House",
  "Deep House",
  "Dancehall",
  "Reggae",
  "Lo-Fi",
  "Other",
];
